### ISSUE TITLE
script that resolves all khan recommendations

### ISSUE THREAD

**Issue by tiagoarodrigues55** [adubov1/khanacademy_bot#4]
hello, I created a script where you pass the login and password and it solves all your recommendations from khan, take a look if you find it interesting. https://github.com/tiagoarodrigues55/khanSolver

**Comment by adubov1** [comment]
Hey, cool project! I wanted to let you know that what looks like your real KhanAcademy login (password as well) is present in multiple files in your project. Very nice work though!
